title: Emergency Response Security Group, Electric Consulting LLC
description: Emergency Response Security Group - Boutique Cyber Security Services Since 1337. Offering specialized services in offensive security, malware research, forensics, OSINT, incident response, and more.
